# Generated by Django 4.2.5 on 2023-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
