# Generated by Django 4.2.5 on 2023-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_files_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='url_hash',
            field=models.URLField(blank=True, null=True),
        ),
    ]
