# Generated by Django 4.2.5 on 2023-10-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_files_url_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('user', 'filename')},
        ),
    ]
