# Generated by Django 4.2.5 on 2023-10-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_files_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together=set(),
        ),
    ]
