# Generated by Django 4.2.5 on 2023-10-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_files_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('user', 'filename')},
        ),
    ]
