# Generated by Django 4.2.5 on 2023-10-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_files_filename_alter_files_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('user', 'file')},
        ),
    ]
