# Generated by Django 4.2.5 on 2023-10-16 17:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_files_unique_together_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
